# Generated by Django 3.0.3 on 2023-11-24 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdata',
            name='blog_image_primary',
            field=models.ImageField(default='Null', upload_to=None),
        ),
    ]
