# Generated by Django 3.0.3 on 2023-11-24 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0002_blogdata_blog_image_primary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdata',
            name='blog_image_primary',
            field=models.ImageField(upload_to=''),
        ),
    ]
