# Generated by Django 3.0.3 on 2023-11-27 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0006_auto_20231126_0924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogdata',
            name='blog_content',
        ),
        migrations.AddField(
            model_name='blogdata',
            name='blog_category',
            field=models.CharField(choices=[('Education', 'Education'), ('Finance', 'Finance'), ('Technology', 'Technology'), ('Automobile', 'Automobile'), ('Bollywood', 'Bollywood'), ('Politics', 'Politics')], default='Education', max_length=20),
        ),
        migrations.AddField(
            model_name='blogdata',
            name='blog_content_para_five',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogdata',
            name='blog_content_para_four',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogdata',
            name='blog_content_para_one',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='blogdata',
            name='blog_content_para_three',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='blogdata',
            name='blog_content_para_two',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='blogdata',
            name='inline_link_one',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inline_links_one', to='newsapp.BlogData'),
        ),
        migrations.AddField(
            model_name='blogdata',
            name='inline_link_two',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inline_links_two', to='newsapp.BlogData'),
        ),
        migrations.AddField(
            model_name='blogdata',
            name='related_link_four',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_links_four', to='newsapp.BlogData'),
        ),
        migrations.AddField(
            model_name='blogdata',
            name='related_link_one',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_links_one', to='newsapp.BlogData'),
        ),
        migrations.AddField(
            model_name='blogdata',
            name='related_link_three',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_links_three', to='newsapp.BlogData'),
        ),
        migrations.AddField(
            model_name='blogdata',
            name='related_link_two',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_links_two', to='newsapp.BlogData'),
        ),
    ]
