# Generated by Django 3.0.3 on 2023-11-27 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0007_auto_20231127_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdata',
            name='image_caption',
            field=models.CharField(default='', max_length=256),
        ),
    ]
